return {
	rockcircle = {
		"rock_flintless",
		"stalagmite_tall",
		"stalagmite",
		"rock_flintless",
		"rock2",
		"moonglass_rock",
		"rock_moon",
		"penguin_ice",
	},
	monstercircle = {
		"spider", 
		"squid",
		"hound", 
		"firehound", 
		"icehound", 
		"tallbird",
		"prime_mate", 
		"frog", 
		"merm", 
		"bat", 
		"bee",
	},
	chest = {
		treasurechest = {
			"log",
			"cutgrass",
			"twigs",
		},
		pandoraschest = {
            "lightbulb",
            "poop",
            "rocks",
            "ice",
            "nightmarefuel",
            "boneshard",
            "charcoal",
		},
		dragonflychest = {
            "armorwood",
            "meatballs",
            "ratatouille",
            "healingsalve",
            "spear",
            "tentaclespike",
		},
		minotaurchest = {
	        "ruins_bat",
	        "thulecite",
	        "ruinshat",
	        "armorruins",
	        "thulecite_pieces",
		},
	},
	getplayer = {
		"beefalohat",
		"amulet",
		"armorwood",
		"footballhat",
		"torch",
		"axe",
		"pickaxe",
		"lightbulb",
		"meat",
		"cave_banana",
		"rocks",
		"boards",
		"seeds",
		"goldnugget",
		"shovel",
		"umbrella",
		"heatrock",
		"gunpowder",
	},
}